version: '3'

services:
  lumen-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx

  mysql-app:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lumen
      MYSQL_ROOT_PASSWORD: lumen
    networks:
      - app-network
networks:
  app-network:
    driver: bridge